### ISSUE TITLE
0.50.0 breaks Marquez web UI in Helm chart

### ISSUE THREAD

**Issue by ThijsKoot** [MarquezProject/marquez#2962]
The port for the web UI was made configurable through environment variables (#2838), however the Helm chart has not been adjusted accordingly, leading to the port being undefined as seen in startup logs.

```
[HPM] Proxy created: /api/v1  -> http://marquez:80/
[HPM] Proxy created: /api/v2beta  -> http://marquez:80/
App listening on port undefined!
```

The chart does have `.Values.web.port` but that does not get passed as an environment variable. Should be an easy fix by setting `WEB_PORT` to the same value.

```yaml
# chart/templates/web/deployment.yaml
ports:
  - name: http
    containerPort: {{ .Values.web.port }}
    protocol: TCP
```
