### ISSUE TITLE
Proposal: configurable sources in config.yml

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#698]
With _source_ types defined as an [enum](https://github.com/MarquezProject/marquez/blob/master/src/main/java/marquez/common/models/SourceType.java) , we limit the usefulness of the source [API](https://marquezproject.github.io/marquez/openapi.html#tag/Sources) as outlined by @nkijak in #694:

- Adding to the enum requires a full release of Marquez
- No option exists to configure sources via [`config.yml`](https://github.com/MarquezProject/marquez/blob/master/config.example.yml)

But, we still need the following dataset [API](https://marquezproject.github.io/marquez/openapi.html#tag/Datasets/paths/~1namespaces~1{namespace}~1datasets~1{dataset}/put) guarantees:

* Ensure a dataset is properly linked to its source type. For example: a _stream_ dataset should only be linked to sources like Kafka, Kinesis, etc and **not** PostgreSQL.
* Marquez relies on the source type to validate the allowed data types (`BOOLEAN`, `INTEGER`, etc) for table columns.

## Proposal

Below, we outline our proposed solution.

### Qualifier `Enum`

First, we would need to move away from specific source types (`MYSQL`, `POSTGRESQL`,  etc) to more generic / hierarchical types (=_qualifiers_)  as proposed by @julienledem (see [discussion](https://gitter.im/marquez-project/community?at=5e13aa82e409da486cd725ce)):

   * `DB`: relation databases (MySQL, PostgreSQL, etc)
   * `FILESYSTEM`: distributed file systems (S3, GCP, etc)
   * `STREAM`: event streams (Kafka, Kinesis, etc)

The introduction of qualifiers has the advantage of contextualizing the source while still maintaining the mapping `DB`->`Set<DataType>` needed for validation:

| Source type | Qualifier  | Data Types                                |
|-------------|------------|-------------------------------------------|
| MYSQL       | DB         | [`INTEGER`,`SMALLINT`,`DECIMAL`, **...**] |
| POSTGRESQL  | DB         | [`BIGINT`,`VARCHAR`,`TEXT`, **...**]      |
| KAFKA       | STREAM     | **-**                                     |
| KINESIS     | STREAM     | **-**                                     |
| S3          | FILESYSTEM | **-**                                     |
| GCP         | FILESYSTEM | **-**                                     |

Below we provide an example configuration for the table above: 

### `config.yml`

```yml
# Configure source types
sourceTypes:
  # Add databases and allowed data types
  dbs:
    - type: MySQL
      dataTypes:
        - INTEGER
        - SMALLINT
        - DECIMAL
        # ...
    - type: PostgreSQL
      dataTypes:
        - BIGINT
        - VARCHAR
        - TEXT
        # ...
  # Add streams
  streams:
    - type: Kafka
    - type: Kinesis
  # Add file systems
  filesystems:
    - type: S3
    - type: GCP
```

To summarize:

- Change source type to _string_ 
- Add source qualifier enum: `DB`, `FILESYSTEM`, `STREAM`
- Add configuration support for source types to [`config.yml`](https://github.com/MarquezProject/marquez/blob/master/config.example.yml)

## Example Usage

Let's say we want to catalog a source named `analytics_prod` with the type `REDSHIFT`. We would now need to specify the qualifier `DB` in the API call:

**Request**

```bash
$ curl -X PUT http://localhost:5000/api/v1/sources/analytics_db \
  -H 'Content-Type: application/json' \
  -d '{
        "type": "REDSHIFT",
        "qualifier": "DB",
        "connectionUrl": "jdbc:redshift://example.us-west-2.redshift.amazonaws.com:5439/analytics"
      }'  
``` 
**Response**

```bash
{
  "type": "REDSHIFT",
  "qualifier": "DB",
  "name": "analytics_db",
  "createdAt": "2020-01-09T19:13:00.749Z",
  "updatedAt": "2020-01-09T19:13:00.749Z",
  "connectionUrl": "jdbc:redshift://example.us-west-2.redshift.amazonaws.com:5439/analytics",
  "description": null
}
```

Then, when tables are linked to the source `analytics_prod`, the allowed data types configured for the source will be referenced and used to ensure column types are valid.
