### ISSUE TITLE
Add sources to config.yml

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#707]
Let's add `sources` to `config.yml` to enabling the configuration of sources. The introduction of qualifiers has the advantage of contextualize the source while still maintaining the mapping `DB`**->** `Set<DataType>` needed for validation:

| Source type | Qualifier  | Data Types                                |
|-------------|------------|-------------------------------------------|
| MYSQL       | DB         | [`INTEGER`,`SMALLINT`,`DECIMAL`, **...**] |
| POSTGRESQL  | DB         | [`BIGINT`,`VARCHAR`,`TEXT`, **...**]      |
| KAFKA       | STREAM     | **-**                                     |
| KINESIS     | STREAM     | **-**                                     |
| S3          | FILESYSTEM | **-**                                     |
| GCP         | FILESYSTEM | **-**                                     |

Below we provide an example configuration for the table above: 

### `config.yml`

```yml
# Configure sources
sources:
  # Add databases and allowed data types
  databases:
    - type: MySQL
      dataTypes:
        - INTEGER
        - SMALLINT
        - DECIMAL
        # ...
    - type: PostgreSQL
      dataTypes:
        - BIGINT
        - VARCHAR
        - TEXT
        # ...
  # Add streams
  streams:
    - type: Kafka
    - type: Kinesis
  # Add file systems
  filesystems:
    - type: S3
    - type: GCP
```
