### ISSUE TITLE
Update migration path to marquez/db/migration

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez#738]
Let's provide a migration path override in `config.example.yml` to fix #737 :

```yml
flyway:
  locations:
    - marquez/db/migration
```
